name: Development Environment Deployment

on:
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkut@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # with:
      #   fetch-depth: 0
    
      # name: Setup .Net
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 8.0.x

      - name: Restore Dependecies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore